#!/bin/bash
#PBS -q condo
#PBS -N django_10xMkfastqs
#PBS -l nodes=1:ppn=16
#PBS -l walltime=8:00:00
#PBS -o /home/zhc268/logs/run_10xMkfastqs.out
#PBS -e /home/zhc268/logs/run_10xMkfastqs.err
#PBS -V
#PBS -m abe
#PBS -A epigen-group

# -v pass parameters: run_dir

export PATH=/projects/ps-epigen/software/cellranger-atac-1.0.1/:$PATH

############################################################
## run bcl2fastq @TSCC
############################################################
## prepare variables & directories
out_dir=${run_dir}/Data/Fastqs/
mkdir -p $out_dir

samplesheet="${out_dir}/SampleSheet.csv"

cd $run_dir 
cellranger-atac mkfastq --run=$run_dir --output-dir=$out_dir --localcores=16 --csv $samplesheet --qc 


# create simlink to the seqdata folder
for i in $(awk -v FS=',' '(NR>1){print $2}' $samplesheet)
do
    for i in $(awk -v FS=',' '(NR>1){print $2}' $samplesheet); do find $(pwd) -name "$i" -type d -exec ln -s {} ~/data/seqdata/ \; ;done 
done

