#!/bin/bash
#PBS -q home-epigen
#PBS -N django_10xMkfastqs
#PBS -l nodes=1:ppn=16
#PBS -l walltime=24:00:00
#PBS -l pmem=6gb
#PBS -o /home/zhc268/logs/run_10xMkpipeline.out
#PBS -e /home/zhc268/logs/run_10xMkpipeline.err
#PBS -V
#PBS -m abe
#PBS -A epigen-group

# -v pass parameters: samples

export PATH=/projects/ps-epigen/software/cellranger-atac-1.0.1/:$PATH
WORKDIR="/oasis/tscc/scratch/$(whoami)/outputs/"
FASTQDIR="/projects/ps-epigen/seqdata/"


# select libs 
samplenames=(`cat $samples`)
INPREFIX=${samplenames[${PBS_ARRAYID}*2]} #index start from 0
GENOME=${samplenames[${PBS_ARRAYID}*2+1]}
#OUTDIR="${WORKDIR}${INPREFIX}"

cd $WORKDIR

# determine genomes
case $GENOME in
    mm10)
        genome_dir="/home/zhc268/data/GENOME/mm10/refdata-cellranger-atac-mm10-1.0.1";;
    hg38)
        genome_dir="/home/zhc268/data/GENOME/hg38/refdata-cellranger-atac-GRCh38-1.0.1";;
    *)
        echo "wrong genome input: $GENOME"
        exit 0;;
esac

# prepair fastqs
fastqs="${FASTQDIR}/${INPREFIX}"
echo $fastqs
 [[ ! -d $fastqs ]] && { echo "$fastqs not found"; exit 0; }


# runPipeline
cellranger-atac count --id=$INPREFIX --fastqs=$fastqs --reference=$genome_dir --localcores=16  --mempercore=8
wait

## addtional check
#[[ -z $(find ${OUTDIR}/qc/rep1 -name "*_qc.txt") ]]  && { echo  "pipeline interrupted"; exit 0; }


# runFastQC & fastq_screen
#runFastQC_screen.sh  $INPREFIX
#results_transfer.sh $INPREFIX $(whoami)

# add .finished.txt tag


#qsub -t 0-2 -v samples=$(pwd)/run_2019-01-08_10xatac.txt $(which run10xPipeline.pbs)

