#!/bin/bash
#PBS -q condo
#PBS -N django_10xDemuxRNA
#PBS -l nodes=1:ppn=16
#PBS -l walltime=8:00:00
#PBS -o /home/zhc268/logs/runDemux10xRNA.out
#PBS -e /home/zhc268/logs/runDemux10xRNA.err
#PBS -V
#PBS -m abe
#PBS -A epigen-group

# -v pass parameters: flowcell_id, run_dir
############################################################
## update status to job submitted @VM
############################################################
cmd="source activate django;python \$(which updateRunStatus.py) -s '1' -f $flowcell_id"
ssh zhc268@epigenomics.sdsc.edu $cmd



############################################################
## run bcl2fastq @TSCC
############################################################
## delete last demux info 
[[ -d ${run_dir}/${flowcell_id} ]] && rm -r ${run_dir}/${flowcell_id}  # delete existing folder
[[ -f ${run_dir}/__${flowcell_id}.mro ]] && rm ${run_dir}/__${flowcell_id}.mro  # delete existing folder

## prepare variables & directories
out_dir_sys=${run_dir}/${flowcell_id}/outs/fastq_path/
out_dir=${run_dir}/Data/Fastqs/
mkdir -p ${out_dir}

## prepair reads_cnt_file
reads_cnt_file="${out_dir}/reads_cnt.tsv"
>$reads_cnt_file

## samplesheet
samplesheet="${out_dir}/SampleSheet_I1.csv"
libs=$(awk -v FS=',' '(NR>1){print $2}' $samplesheet)

## run mkfastq 
cd $run_dir
export PATH=/projects/ps-epigen/software/cellranger-3.0.2/:$PATH

[[ -f ${out_dir}/extraPars.txt ]] && extraParsVal=$(cat ${out_dir}/extraPars.txt)
echo -e "cellranger-atac mkfastq --run=$run_dir  --localcores=16 --csv $samplesheet --qc $extraParsVal #--use-bases-mask Y50,I8n*,Y16,Y50"
cellranger mkfastq --run=$run_dir  --localcores=16 --csv $samplesheet --qc $extraParsVal #--use-bases-mask Y50,I8n*,Y16,Y50

## transfer/link data
ln -sf ${out_dir_sys}/Stats $out_dir
ln -sf ${out_dir_sys}/Stats $out_dir
for i in $libs
do
    #cp -r ${out_dir_sys}/$flowcell_id/${i} ~/data/seqdata/
    ln -sf ${out_dir_sys}/${flowcell_id}/${i} ~/data/seqdata/
    cat ~/data/seqdata/${i}/${i}*R2*fastq.gz > ~/data/seqdata/${i}_R2.fastq.gz & sleep 1
    cat ~/data/seqdata/${i}/${i}*R1*fastq.gz > ~/data/seqdata/${i}_R1.fastq.gz & sleep 1
    wait 
    nreads=$(zcat ~/data/seqdata/${i}_R1.fastq.gz | wc -l ) && echo -e "$i\t$[nreads/4]" >> $reads_cnt_file & sleep 1
done 
wait 
############################################################
# update status to finish or warning @ VM
############################################################
cmd="source activate django; python \$(which updateReadsNumberPerRun.py) -f $flowcell_id -i $reads_cnt_file; python \$(which updateRunReads.py) -f $flowcell_id"
job1=$(ssh zhc268@epigenomics.sdsc.edu $cmd)

############################################################
# run 10x pipeline
############################################################

#qsub -t 0-1 -v samples=${HOME}/runlogs/run_2019-01-22_10xatac_modifiedPeakPar.txt $(which run10xPipeline.pbs)
