#!/bin/bash
#PBS -q condo
#PBS -N django_10xDemux
#PBS -l nodes=1:ppn=16
#PBS -l walltime=8:00:00
#PBS -o /home/zhc268/logs/runDemux10xATAC.out
#PBS -e /home/zhc268/logs/runDemux10xATAC.err
#PBS -V
#PBS -m abe
#PBS -A epigen-group

# -v pass parameters: flowcell_id, run_dir
############################################################
## update status to job submitted @VM
############################################################
cmd="source activate django;python \$(which updateRunStatus.py) -s '1' -f $flowcell_id"
ssh zhc268@epigenomics.sdsc.edu $cmd



############################################################
## run bcl2fastq @TSCC
############################################################
## prepare variables & directories
out_dir=${run_dir}/Data/Fastqs/
mkdir -p $out_dir

## prepair reads_cnt_file
reads_cnt_file="${out_dir}/reads_cnt.tsv"
>$reads_cnt_file

## samplesheet
samplesheet="${out_dir}/SampleSheet_I1.csv"
libs=$(awk -v FS=',' '(NR>1){print $2}' $samplesheet)

## run mkfastq 
cd $run_dir
export PATH=/projects/ps-epigen/software/cellranger-atac-1.0.1/:$PATH
cellranger-atac mkfastq --run=$run_dir --output-dir=$out_dir --localcores=16 --csv $samplesheet --qc 

## transfer/link data
for i in $libs;do ln -s ${out_dir}/$flowcell_id/${i} ~/data/seqdata/;done 

############################################################
# update status to finish or warning @ VM
############################################################
cmd="source activate django; python \$(which updateReadsNumberPerRun.py) -f $flowcell_id -i $reads_cnt_file; python \$(which updateRunReads.py) -f $flowcell_id"
ssh zhc268@epigenomics.sdsc.edu $cmd

############################################################
# run 10x pipeline
############################################################
#qsub -t 0-1 -v samples=${HOME}/runlogs/run_2019-01-22_10xatac_modifiedPeakPar.txt $(which run10xPipeline.pbs)
