#!/bin/bash 
#PBS -q home
#PBS -N runFastQC-JYH
#PBS -l nodes=1:ppn=1
#PBS -l walltime=1:00:00
#PBS -o /home/zhc268/logs/runFastQC-JYH.out
#PBS -e /home/zhc268/logs/runFastQC-JYH.err
#PBS -V
#PBS -A epigen-group



#!/bin/bash 
# run fastq QC for _2 libs/seq runs 
module load fastqc

FASTQ_DIR="/projects/ps-epigen/seqdata/"
sample_prefix="JYH_"$PBS_ARRAYID"_2"

OUTPUT_DIR="/projects/ps-epigen/outputs/libQCs/"${sample_prefix}
mkdir -p $OUTPUT_DIR

fastq1=${FASTQ_DIR}${sample_prefix}"_R1.trim.fastq.gz"
fastq2=${FASTQ_DIR}${sample_prefix}"_R2.trim.fastq.gz"

fastqc  -outdir $OUTPUT_DIR  $fastq1
fastqc  -outdir $OUTPUT_DIR  $fastq2



